name: RelayRace
description: Survive in relay until you clear the game.
author: Dainsleif
version: '${version}'
main: top.syshub.relayRace.RelayRace
api-version: '26.1.2'
load: POSTWORLD

permissions:
  relayrace.command:
    description: Allows use of /relayrace commands
    default: op
