name: RelayRace
description: Survive in relay until you clear the game.
author: Dainsleif
version: '${version}'
main: top.syshub.relayrace.common.RelayRacePlugin
api-version: '1.16'
load: POSTWORLD

permissions:
  relayrace.command:
    description: Allows use of /relayrace commands
    default: op
